
module.exports.categories = [
  {
    name: 'clothes'
  },
  {
    name: 'toys'
  },
  {
    name: 'cat toys'
  }
];

module.exports.products = [
  {
    name: 'Wand Tassels The Mouse Cat Toy',
    description: 'stick to wave in front of your cat',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.23.14+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '3.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 30
  },
  {
    name: 'SmartyKat Skitter Critters Catnip Mice',
    description: 'mice covered in catnip',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.23.23+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '8.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 81
  },
  {
    name: 'Teasel Cat Tunnel',
    description: 'fun tunnel for cats',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.23.32+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '8.99',
    cutPrice: null,
    rating: '3.0',
    reviewCount: 27
  },
  {
    name: 'Smarty Kat Carrot',
    description: 'cat chew toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.23.37+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'SmartyKat Loco Laser',
    description: 'laser',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.23.42+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '7.99',
    cutPrice: null,
    rating: '3.5',
    reviewCount: 54
  },
  {
    name: 'Smarty Kat Silly Swimmers',
    description: 'feather toys',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.23.51+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '8.99',
    cutPrice: null,
    rating: '2.0',
    reviewCount: 18
  },
  {
    name: 'Furry Poms Cat Toy - 2pk',
    description: 'pom poms',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.24.02+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 10
  },
  {
    name: 'Boots & Barkley Catnip Pounce Sloth',
    description: 'catnip infused sloth',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.24.08+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '2.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 14
  },
  {
    name: 'SmartyKat Flutter Roller',
    description: 'rolling ringing toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.24.16+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '8.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 23
  },
  {
    name: 'Platypus Cat Toy',
    description: 'platypus cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.24.20+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '2.99',
    cutPrice: '0.99',
    rating: '5.0',
    reviewCount: 29
  },
  {
    name: 'Ball Track Cat Scratcher',
    description: 'cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.24.25+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '10.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 33
  },
  {
    name: 'Tunnel Cat Scratcher',
    description: 'cat tunnel of fun',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.24.35+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '8.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 55
  },
  {
    name: 'Rubber Lattice Tie Dye Cat Toy',
    description: 'bell balls',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.06+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '4.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 7
  },
  {
    name: 'SmartyKat Chitter Critter',
    description: 'electronic sound cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.12+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '5.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 50
  },
  {
    name: 'Quirky Kitty Pineapple & Flamingo Cat Toy',
    description: 'stuffed toys',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.22+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '3.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 10
  },
  {
    name: 'Tassel Wand Cat Toy',
    description: 'tassel tassel',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.27+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '8.99',
    cutPrice: '2.99',
    rating: '3.0',
    reviewCount: 28
  },
  {
    name: 'Quirky Kitty Avacado Toast',
    description: 'cats like avacados',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.33+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '3.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 16
  },
  {
    name: 'SmartyKat Chit Chatter',
    description: 'electronic sound cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.41+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '4.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 9
  },
  {
    name: 'SmartyKat Leggy Llama',
    description: 'catnip cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.46+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '4.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 24
  },
  {
    name: 'SmartyKat Madcap Mania Catnip',
    description: 'refillable cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.35.52+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '8.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'SmartyKat Fuzzy Friends',
    description: 'catnip cat toy, set of 2',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.36.00+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Cat Wave Scratcher',
    description: 'cat scratcher tunnel',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.36.06+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: '0.99',
    rating: null,
    reviewCount: null
  },
  {
    name: 'Taco Truck Cat Scratcher',
    description: 'cat house',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.36.13+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '24.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'SmartyKat Race \'N\' Chase',
    description: '',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.36.32+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: null,
    rating: '3.0',
    reviewCount: 31
  },
  {
    name: 'SmartyKat Skitter Critters',
    description: 'stuffed mice',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.36.38+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '6.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 13
  },
  {
    name: 'Gift Holiday Cat Stocking Toy Set',
    description: 'stocking stuffer for you cat',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.36.45+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '10.00',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'SmartyKat Smarty Stash',
    description: 'variety kat toys',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.36.54+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '6.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 13
  },
  {
    name: 'Hot Chocolate Mice Holiday',
    description: 'marshmellow mice and toy mug',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.02+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '6.00',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 18
  },
  {
    name: 'SmartyKat Silly Swinger',
    description: 'tasel toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.09+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '3.99',
    cutPrice: null,
    rating: '2.5',
    reviewCount: 3
  },
  {
    name: 'SmartyKat Catnip',
    description: 'silvernine blend catnip',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.16+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.49',
    cutPrice: '1.99',
    rating: '4.5',
    reviewCount: 42
  },
  {
    name: 'Tweedle and Dee',
    description: 'soft cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.22+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 9
  },
  {
    name: 'SmartyKat Magic Mice',
    description: 'catnip mice',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.28+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '9.99',
    cutPrice: '4.99',
    rating: '5.0',
    reviewCount: 14
  },
  {
    name: 'Colerful Bulbs',
    description: 'holiday cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.34+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 6
  },
  {
    name: 'Colorful Teaser',
    description: 'tasel toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.53+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 12
  },
  {
    name: 'SmartyKat Window Wobbler',
    description: 'suction cup fun',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.37.59+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: '2.5',
    reviewCount: 45
  },
  {
    name: 'SmartyKat Stix',
    description: '100% catnip',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.38.39+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Glitter Fish Tacos',
    description: '2pk',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.39.27+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '2.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 20
  },
  {
    name: 'SmartyKat Marble Mouse Roller',
    description: 'wobbling mouse toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.39.34+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '3.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 15
  },
  {
    name: 'SmartyKat Cat Post',
    description: 'scratching post',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.39.41+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '24.99',
    cutPrice: '19.99',
    rating: '4.0',
    reviewCount: 21
  },
  {
    name: 'Cat Scracher - Tan - XL',
    description: 'cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.39.49+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '9.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 6
  },
  {
    name: 'SmartyKat Sisal Angle Cat Scratcher',
    description: 'cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.39.54+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: null,
    rating: '3.0',
    reviewCount: 24
  },
  {
    name: 'Double Decker Holiday Tree',
    description: 'cat scratcher house',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.40.01+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '34.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Double Decker Holiday Present',
    description: 'cat scratcher house',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.40.09+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '34.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'SmartyKat Hot Pursuit',
    description: 'electronic light and motion cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.40.17+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '16.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 85
  },
  {
    name: 'SmartyKat Fishy Fun',
    description: 'crinkle catnip',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.40.23+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '8.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 15
  },
  {
    name: 'Corrugate Cat Scratch Ottoman',
    description: 'fun for everyone',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+2.40.36+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '19.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 49
  },
  {
    name: 'Pirate Ship',
    description: 'cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.38.36+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '34.99',
    cutPrice: null,
    rating: '3.0',
    reviewCount: 90
  },
  {
    name: 'Catit Play Tumbler',
    description: 'bee cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.38.48+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '29.99',
    cutPrice: null,
    rating: '3.5',
    reviewCount: 2
  },
  {
    name: 'Basic Cat Scratcher',
    description: 'black cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.38.54+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '5.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 6
  },
  {
    name: 'Fun House',
    description: 'cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.39.01+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '16.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 49
  },
  {
    name: 'Catit Play Circuit',
    description: 'ball with catnip',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.39.10+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '24.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Premier Pet - Laser Cat Toy',
    description: 'laser laser',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.39.15+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '17.99',
    cutPrice: '10.99',
    rating: '4.5',
    reviewCount: 216
  },
  {
    name: 'SmartyKat Super Scratcher',
    description: 'chaise catnip infused',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.39.21+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 105
  },
  {
    name: 'Catit Vesper Tunnel',
    description: 'cat tunnel',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.39.30+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '39.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'SmartyKat Silly Spinner',
    description: 'electronic light and motion cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.39.36+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '9.99',
    cutPrice: '5.99',
    rating: '4.0',
    reviewCount: 11
  },
  {
    name: 'Quirky Kitty Unicorn',
    description: 'stuffed unicorn cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.41.26+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '3.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 3
  },
  {
    name: 'SmartyKat Silvernine Catnip',
    description: 'catnip refiller',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.41.39+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '5.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 16
  },
  {
    name: 'Quirky Kitty Chicken & Tuna Cat Toy',
    description: 'stuffed cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.42.41+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '3.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 7
  },
  {
    name: 'SmartyKat Crinkle Cloud',
    description: 'cat mat',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.42.53+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '7.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 30
  },
  {
    name: 'Catit Vesper Rocket Cat Toy',
    description: 'cat house',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.43.01+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '55.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Cat-Life Play Tree',
    description: 'carpet scratching post',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.43.08+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '33.99',
    cutPrice: null,
    rating: '3.0',
    reviewCount: 5
  },
  {
    name: 'Catit Play Circuit',
    description: 'ball cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.43.46+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '24.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Hauspanther Nest Perch',
    description: 'hanging cat perch scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.43.53+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '49.99',
    cutPrice: '1.99',
    rating: '5.0',
    reviewCount: 1
  },
  {
    name: 'Way Basics Eco Cube',
    description: 'cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.44.01+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '24.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 4
  },
  {
    name: 'Hauspanther Dual Surface Pole Cat Scratcher',
    description: 'pole cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.44.07+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '24.99',
    cutPrice: null,
    rating: '3.0',
    reviewCount: 1
  },
  {
    name: 'A-Frame Cat Scratcher',
    description: 'corrugate',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.44.14+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '19.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 11
  },
  {
    name: 'Catit Play Circuit',
    description: 'ball toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.44.41+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '19.99',
    cutPrice: null,
    rating: '2.5',
    reviewCount: 37
  },
  {
    name: 'Trixie Belinda Cat Playground',
    description: 'cat playgound',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.44.47+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '225.00',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 7
  },
  {
    name: 'Pet Genius Smart Play Rover Cart Toy',
    description: 'rolling dangle toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.44.53+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '19.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 1
  },
  {
    name: 'SmartyKat Tweet Tower',
    description: 'cat scratch post',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.45.01+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '19.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 12
  },
  {
    name: 'Catit Senses Grass Planter',
    description: 'put your cat outside to enjoy grass',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.45.08+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: null,
    rating: '1.5',
    reviewCount: 1
  },
  {
    name: 'SmartyKat Triple Tower',
    description: '3 pack cat scratch towers',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.45.14+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '24.99',
    cutPrice: '19.99',
    rating: '4.0',
    reviewCount: 42
  },
  {
    name: 'Catit Vesper Cubo',
    description: 'cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.45.22+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '99.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 3
  },
  {
    name: 'Hauspanther CATchall',
    description: 'wall cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.45.28+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '49.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 15
  },
  {
    name: 'Catit Vesper Cube Slim',
    description: 'cat house scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.45.42+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '50.99',
    cutPrice: null,
    rating: '3.5',
    reviewCount: 4
  },
  {
    name: 'Catit Play Treast Spinner Cat Toy',
    description: 'spinning cat treat feeder',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.02+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '13.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 2
  },
  {
    name: 'B. Toys Interactive Plush',
    description: 'wobble and go toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.11+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '16.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 44
  },
  {
    name: 'Trixie Alicante Cat Tree',
    description: 'cat play thing',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.18+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '99.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 3
  },
  {
    name: 'Catit Vesper Rocket',
    description: 'cat house',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.25+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '59.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 3
  },
  {
    name: 'Catit Play Pirates Cannon',
    description: 'cat cannon tunnel',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.31+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '28.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Majestic Pet Activity Center',
    description: 'cat tower scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.37+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '56.99',
    cutPrice: null,
    rating: '3.5',
    reviewCount: 6
  },
  {
    name: 'Hauspanther Nest Perch',
    description: 'cat wall perch scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.44+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '49.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 12
  },
  {
    name: 'Penguin Kicker',
    description: 'holiday cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.50+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '4.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 5
  },
  {
    name: 'Cat-Life Multi-Level Lounger',
    description: 'cat bamboo tower scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.46.57+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '66.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 3
  },
  {
    name: 'Rainbow Double Cat Scratcher',
    description: 'cat tunnel scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.47.21+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '16.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 33
  },
  {
    name: 'Cat Scratcher House',
    description: 'cat home ammenities',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.47.31+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 32
  },
  {
    name: 'Geo Tent Cat Scratcher',
    description: 'cat scratcher tent',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.47.48+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: null,
    rating: '1.5',
    reviewCount: 2
  },
  {
    name: 'Crowded Coop, LLC Star Trek Tribble',
    description: 'star trek cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.48.05+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '12.00',
    cutPrice: null,
    rating: '4.0',
    reviewCount: 2
  },
  {
    name: 'Valentine\'s Day Cat Scratcher',
    description: 'cat home scratcher valentine themed',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.48.14+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '16.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 2
  },
  {
    name: 'SmartyKat Silvernine & Catnip Blend',
    description: 'catnip refill',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.48.56+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '1.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 15
  },
  {
    name: 'FurHaven Corrugated House Cat Scratcher',
    description: 'cat house scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.49.05+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '22.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 1
  },
  {
    name: 'Pestiges Mousin Around',
    description: 'hide n treat cat toy',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.49.18+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '12.99',
    cutPrice: null,
    rating: '2.0',
    reviewCount: 1
  },
  {
    name: 'Parla Scratching Post',
    description: 'scratching post, what else ya need?',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.51.26+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '19.49',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 15
  },
  {
    name: 'Majestic Cat Casita Faux Fur Activity Center',
    description: 'you love your cat dont you?',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.51.36+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '68.99',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Pestiges Grass Patch Hunting Box',
    description: 'i think mice pop out of the holes',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.51.41+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '17.59',
    cutPrice: null,
    rating: null,
    reviewCount: null
  },
  {
    name: 'Pestiges Easy Life Snuggle and Rest',
    description: 'cat relax and scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.51.46+PM.webp',
    category: 3,
    isFavorite: 1,
    price: '19.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 1
  },
  {
    name: 'Pestages Wobble Track Cat Toy',
    description: 'wobble wobble tassel wand',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.52.00+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '19.99',
    cutPrice: null,
    rating: '1.5',
    reviewCount: 2
  },
  {
    name: 'Pestages Scratch and Play Tower Track',
    description: 'cat scratcher tower with track and ball',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.52.07+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '19.99',
    cutPrice: null,
    rating: '3.0',
    reviewCount: 5
  },
  {
    name: 'Two By Two Elm Cat Tower',
    description: 'cat scratch tower and ball',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.52.28+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '29.99',
    cutPrice: null,
    rating: '5.0',
    reviewCount: 3
  },
  {
    name: 'Catit Style Catnip Bench',
    description: 'catnip cat scratcher',
    imageUrl: 'https://carousel-media.s3.us-east-2.amazonaws.com/carousel-media/Screen+Shot+2021-01-13+at+3.52.40+PM.webp',
    category: 3,
    isFavorite: 0,
    price: '14.99',
    cutPrice: null,
    rating: '4.5',
    reviewCount: 2
  }
];